spring:
    profiles:
        active: dev
    config:
        import: "optional:configserver:http://localhost:8888"
    application:
        name: calendar
    cloud:
        config:
            uri: http://localhost:8888

server:
    port: 8081

eureka:
  client:
    service-url: 
        default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
        instance:
            prefer-ip-address: true
