spring:
    application:
        name: calendar
    datasource:
        url: jdbc:postgresql://localhost:5481/calendar
        username: postgres   
        password: postgres   
    jpa:
        show-sql: true    
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate: 
            ddl-auto: update            

server:
    port: 8081
    instance:
        id: 1    

logging:
  level: 
    it.overzoom.eq.calendar.feign: DEBUG

springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui-custom.html  
        operationsSorter: method

message:
    welcome: Hello Properties Dev

          
