spring:
    application:
        name: calendar
    datasource:
        url: jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5481}/calendar
        username: ${RDS_USERNAME:postgres}   
        password: ${RDS_PASSWORD:postgres}   
    jpa:
        show-sql: true    
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate: 
            ddl-auto: update     

server:
    port: 8081
    instance:
        id: 1    

openapi:
    service:
        title: calendar doc
        version: 1.0.0
        url: http://localhost:8765

logging:
  level: 
    it.overzoom.eq.calendar.feign: DEBUG

springdoc:
    api-docs:
        path: /calendar/api-docs
    swagger-ui:
        path: /calendar/swagger-ui.html  
        operationsSorter: method

message:
    welcome: Hello Properties Dev

eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
        prefer-ip-address: true                 