spring:
    profiles:
        active: dev
    config:
        import: "optional:configserver:http://localhost:8888"
    application:
        name: calendar
    cloud:
        config:
            uri: http://localhost:8888


server:
    port: 8081
