services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot      
    restart: unless-stopped
    command: /bin/sh -c "while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g 'daemon off;'"  
    networks:
      - eq_net   

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: unless-stopped
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;" 
    depends_on:
      - nginx 
    networks:
      - eq_net  

  eurekaserver:
    build:
      context: ./eurekaserver
      dockerfile: Dockerfile
    image: eurekaserver:latest
    container_name: eurekaserver
    restart: always
    ports:
      - "8761:8761"
    environment:
      EUREKA_CLIENT_REGISTER-WITH-EUREKA: false
      EUREKA_CLIENT_FETCH-REGISTRY: false  
    networks:
      - eq_net

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    image: gateway:latest
    container_name: gateway
    restart: always
    ports:
      - "8765:8765"
    env_file:
      - .env  
    depends_on:
      eurekaserver:
        condition: service_started
    networks:
      - eq_net

  registrydb:
    image: mongo
    container_name: registrydb
    restart: always
    logging:
      options:
        max-size: 200m
    ports:
      - "5480:27017"
    volumes:
      - registrydb:/data/db  
    env_file:
      - .env
    networks:
      - eq_net  

  registry:
    build:
      context: ./registry
      dockerfile: Dockerfile
    image: registry:latest
    container_name: registry
    restart: always
    env_file:
      - .env
    depends_on:
      eurekaserver:
        condition: service_started
      registrydb:
        condition: service_started
    networks:
      - eq_net    

  calendardb:
    image: postgres
    container_name: calendardb
    restart: always
    shm_size: 128mb
    ports:
      - "5481:5432"
    volumes:
      - calendardb:/data/postgres  
    env_file:
      - .env
    networks:
      - eq_net

  calendar:
    build:
      context: ./calendar
      dockerfile: Dockerfile
    image: calendar:latest
    container_name: calendar
    restart: always
    env_file:
      - .env
    depends_on:
      eurekaserver:
        condition: service_started
      calendardb:
        condition: service_started
    networks:
      - eq_net

  document:
    build:
      context: ./document
      dockerfile: Dockerfile
    image: document:latest
    container_name: document
    restart: always
    ports:
      - "8082:8082"
    env_file:
      - .env
    depends_on:
      eurekaserver:
        condition: service_started
    networks:
      - eq_net    

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - gateway
    networks:
      - eq_net

networks:
  eq_net:
    driver: bridge

volumes:
  gatewaydb:
  registrydb:
  calendardb:
