services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    mem_limit: 2g      
    mem_reservation: 1g 
    networks:
      - eq_net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.1
    container_name: logstash
    depends_on:
      - elasticsearch
    ports:
      - "5000:5000"
      - "9600:9600"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    mem_limit: 1g       
    mem_reservation: 512m
    networks:
      - eq_net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.1
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=${KIBANA_ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${KIBANA_ELASTICSEARCH_PASSWORD}
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    mem_limit: 1g       
    mem_reservation: 512m
    networks:
      - eq_net

  gateway:
    image: overzoom/eq_gateway:latest
    container_name: gateway
    mem_limit: 512m     
    mem_reservation: 256m
    ports:
      - "8765:8765"
    env_file:
      - .env
    depends_on:
      - eurekaserver
    networks:
      - eq_net

  registry:
    image: overzoom/eq_registry:latest
    container_name: registry
    mem_limit: 512m
    mem_reservation: 256m
    env_file:
      - .env
    depends_on:
      - eurekaserver
      - registrydb
    networks:
      - eq_net

  calendar:
    image: overzoom/eq_calendar:latest
    container_name: calendar
    mem_limit: 512m
    mem_reservation: 256m
    env_file:
      - .env
    depends_on:
      - eurekaserver
      - calendardb
    networks:
      - eq_net

  document:
    image: overzoom/eq_document:latest
    container_name: document
    ports:
      - "8082:8082"
    mem_limit: 512m
    mem_reservation: 256m
    env_file:
      - .env
    depends_on:
      - eurekaserver
    networks:
      - eq_net

  frontend:
    image: overzoom/eq_frontend:latest
    container_name: frontend
    ports:
      - "4200:80"
    mem_limit: 256m  
    mem_reservation: 128m
    depends_on:
      - gateway
    networks:
      - eq_net

  eurekaserver:
    image: overzoom/eq_eurekaserver:latest
    container_name: eurekaserver
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      EUREKA_CLIENT_REGISTER-WITH-EUREKA: false
      EUREKA_CLIENT_FETCH-REGISTRY: false
    ports:
      - "8761:8761"
    networks:
      - eq_net

  registrydb:
    image: mongo
    container_name: registrydb
    mem_limit: 512m
    mem_reservation: 256m
    logging:
      options:
        max-size: 200m
    ports:
      - "5480:27017"
    volumes:
      - registrydb:/data/db
    env_file:
      - .env
    networks:
      - eq_net

  calendardb:
    image: postgres
    container_name: calendardb
    mem_limit: 512m
    mem_reservation: 256m
    shm_size: 128mb
    ports:
      - "5481:5432"
    volumes:
      - calendardb:/data/postgres
    env_file:
      - .env
    networks:
      - eq_net

networks:
  eq_net:
    driver: bridge

volumes:
  esdata:
  registrydb:
  calendardb:
