services:
  # ———————— Ingress / Certbot ————————
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: unless-stopped
    command: /bin/sh -c "while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g 'daemon off;'"
    networks:
      - eq_net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: unless-stopped
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"
    depends_on:
      - nginx
    networks:
      - eq_net

  # ———————— Eureka & Gateway & Microservizi ————————
  eurekaserver:
    image: overzoom/eq_eurekaserver:latest
    container_name: eurekaserver
    restart: always
    ports:
      - "8761:8761"
    environment:
      EUREKA_CLIENT_REGISTER-WITH-EUREKA: false
      EUREKA_CLIENT_FETCH-REGISTRY: false
    networks:
      - eq_net

  gateway:
    image: overzoom/eq_gateway:latest
    container_name: gateway
    restart: always
    ports:
      - "8765:8765"
    env_file:
      - .env
    depends_on:
      - eurekaserver
    networks:
      - eq_net

  registrydb:
    image: mongo
    container_name: registrydb
    restart: always
    logging:
      options:
        max-size: 200m
    ports:
      - "5480:27017"
    volumes:
      - registrydb:/data/db
    env_file:
      - .env
    networks:
      - eq_net

  registry:
    image: overzoom/eq_registry:latest
    container_name: registry
    restart: always
    env_file:
      - .env
    depends_on:
      - eurekaserver
      - registrydb
    networks:
      - eq_net

  calendardb:
    image: postgres
    container_name: calendardb
    restart: always
    shm_size: 128mb
    ports:
      - "5481:5432"
    volumes:
      - calendardb:/data/postgres
    env_file:
      - .env
    networks:
      - eq_net

  calendar:
    image: overzoom/eq_calendar:latest
    container_name: calendar
    restart: always
    env_file:
      - .env
    depends_on:
      - eurekaserver
      - calendardb
    networks:
      - eq_net

  document:
    image: overzoom/eq_document:latest
    container_name: document
    restart: always
    ports:
      - "8082:8082"
    env_file:
      - .env
    depends_on:
      - eurekaserver
    networks:
      - eq_net

  frontend:
    image: overzoom/eq_frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - gateway
    networks:
      - eq_net

  # ———————— ELK Stack ————————
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - eq_net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.1
    container_name: logstash
    depends_on:
      - elasticsearch
    ports:
      - "5000:5000"      # endpoint TCP JSON
      - "9600:9600"      # monitoring API
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    networks:
      - eq_net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.1
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    networks:
      - eq_net

networks:
  eq_net:
    driver: bridge

volumes:
  gatewaydb:
  registrydb:
  calendardb:
  esdata:
