server:
    port: 8765

spring:
    application:
        name: gateway 
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:5050/realms/EQ

    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true    
            routes[0]:
                    predicates[0]: Path=/api/registry/** , /registry/api-docs       
                    uri: lb://REGISTRY        
            routes[1]:
                    predicates[0]: Path=/api/calendar/** , /calendar/api-docs       
                    uri: lb://CALENDAR    


openapi:
    service:
        title: gateway doc
        version: 1.0.0
        url: http://localhost:8765

springdoc:
    enable-native-support: true
    api-docs:
        enabled: true
        path: /api-docs
    swagger-ui:
        enabled: true
        path: /swagger-ui.html
        config-url: /api-docs/swagger-config
        operationsSorter: method
        urls:
        - url: /api-docs
          name: Gateway Microservice
        - url: /calendar/api-docs
          name: Calendar Microservice
        - url: /registry/api-docs
          name: Registry Microservice

keycloak:
  auth-server-url: ${KEYCLOAK_URI:http://localhost:5050}
  realm: EQ
  resource: eq-project
  admin:
    realm: master
    resource: admin-cli

frontend:
    origin-url: ${FRONTEND_URI:http://localhost:4200}

eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
        prefer-ip-address: true
        
      