server:
    port: 8765

spring:
    application:
        name: gateway 
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${KEYCLOAK_URI:http://localhost:5050}/realms/EQ

    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true    
            routes[0]:
                    predicates[0]: Path=/api/registry/** , /registry/api-docs       
                    uri: lb://REGISTRY        
            routes[1]:
                    predicates[0]: Path=/api/calendar/** , /calendar/api-docs       
                    uri: lb://CALENDAR              
            routes[2]:
                    predicates[0]: Path=/api/document/** , /document/api-docs       
                    uri: lb://DOCUMENT                                


openapi:
    service:
        title: gateway doc
        version: 1.0.0
        url: http://localhost:8765

springdoc:
    enable-native-support: true
    api-docs:
        enabled: true
        path: /api-docs
    swagger-ui:
        enabled: true
        path: /swagger-ui.html
        config-url: /api-docs/swagger-config
        operationsSorter: method
        urls:
        - url: /api-docs
          name: API Gateway Microservice
        - url: /calendar/api-docs
          name: Calendar Microservice
        - url: /registry/api-docs
          name: Registry Microservice
        - url: /document/api-docs
          name: Document Microservice  

keycloak:
  auth-server-url: ${KEYCLOAK_URI:http://localhost:5050}
  realm: EQ
  resource: eq-project
  admin:
    realm: master
    resource: admin-cli    
    username: admin
    password: admin

eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
        prefer-ip-address: true
        
      