server:
    port: 8765

spring:
    application:
        name: gateway 
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:5050/realms/EQ

    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true    
            routes[0]:
                    predicates[0]: Path=/api/registry/** , /registry/api-docs       
                    uri: lb://REGISTRY        
            routes[1]:
                    predicates[0]: Path=/api/calendar/** , /calendar/api-docs       
                    uri: lb://CALENDAR    

springdoc:
    enable-native-support: true
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true
        path: /swagger-ui.html
        config-url: /api-docs/swagger-config
        urls:
        - url: /api-docs
          name: API Gateway Service
        - url: /calendar/api-docs
          name: Calendar Service
        - url: /registry/api-docs
          name: Registry Service

keycloak:
  auth-server-url: ${KEYCLOAK_URI:http://localhost:5050}
  realm: EQ
  resource: eq-project
  credentials:
    secret: 

eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
        prefer-ip-address: true
        
      