server:
    port: 8765

spring:
    application:
        name: gateway 
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: https://cognito-idp.${COGNITO_REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}/.well-known/jwks.json                        

    cloud:
        gateway:
            default-filters:
                - TokenRelay
            discovery:
                locator:
                    enabled: true    
            routes[0]:
                    predicates[0]: Path=/api/registry/** , /registry/api-docs       
                    uri: lb://REGISTRY        
            routes[1]:
                    predicates[0]: Path=/api/calendar/** , /calendar/api-docs       
                    uri: lb://CALENDAR              
            routes[2]:
                    predicates[0]: Path=/api/document/** , /document/api-docs       
                    uri: lb://DOCUMENT                                


cognito:
  region: eu-central-1
  client-id: 7tjsnvadbdm0413v71uku5h425

openapi:
    service:
        title: gateway doc
        version: 1.0.0
        url: http://localhost:8765

springdoc:
    enable-native-support: true
    api-docs:
        enabled: true
        path: /api-docs
    swagger-ui:
        enabled: true
        path: /swagger-ui.html
        config-url: /api-docs/swagger-config
        operationsSorter: method
        urls:
        - url: /api-docs
          name: API Gateway Microservice
        - url: /calendar/api-docs
          name: Calendar Microservice
        - url: /registry/api-docs
          name: Registry Microservice
        - url: /document/api-docs
          name: Document Microservice  

eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
        prefer-ip-address: true
        
      