spring:
    application:
        name: gateway 
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true    
            routes[0]:
                    predicates[0]: Path=/api/registry/**        
                    uri: lb://REGISTRY        
            routes[1]:
                    predicates[0]: Path=/api/calendar/**        
                    uri: lb://CALENDAR
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_mE1PCCeYh                
            

server:
    port: 8765
