server:
    port: 8765

spring:
    application:
        name: gateway 
    datasource:
        url: jdbc:postgresql://${GATEWAYDB_HOST:gatewaydb}:${GATEWAYDB_PORT:5432}/${GATEWAYDB_DB_NAME:gateway}
        username: ${GATEWAYDB_USER:postgres}
        password: ${GATEWAYDB_PASSWORD:postgres}
    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true    
    security:
        oauth2:
            client:
                registration:
                    cognito:
                        client-id: ${COGNITO_CLIENT_ID}
                        client-secret: ${COGNITO_CLIENT_SECRET}
                        authorization-grant-type: authorization_code
                        redirect-uri: "https://api.radpro.it/login/oauth2/code/cognito"
                        scope:
                        - openid
                        - email
                        - profile
                provider:
                    cognito:
                        authorization-uri: ${COGNITO_DOMAIN}/oauth2/authorize
                        token-uri:         ${COGNITO_DOMAIN}/oauth2/token
                        user-info-uri:     ${COGNITO_DOMAIN}/oauth2/userInfo
                        jwk-set-uri:       https://cognito-idp.eu-central-1.amazonaws.com/${COGNITO_USER_POOL_ID}/.well-known/jwks.json
            resourceserver:
                jwt:
                    jwk-set-uri: https://cognito-idp.eu-central-1.amazonaws.com/${COGNITO_USER_POOL_ID}/.well-known/jwks.json
            


    cloud:
        gateway:
            default-filters:
                - TokenRelay
            discovery:
                locator:
                    enabled: true    
            routes[0]:
                    predicates[0]: Path=/api/registry/** , /registry/api-docs       
                    uri: lb://REGISTRY        
            routes[1]:
                    predicates[0]: Path=/api/calendar/** , /calendar/api-docs       
                    uri: lb://CALENDAR              
            routes[2]:
                    predicates[0]: Path=/api/document/** , /document/api-docs       
                    uri: lb://DOCUMENT                                

 
openapi:
    service:
        title: gateway doc
        version: 1.0.0
        url: http://localhost:8765

springdoc:
    enable-native-support: true
    api-docs:
        enabled: true
        path: /api-docs
    swagger-ui:
        enabled: true
        path: /swagger-ui.html
        config-url: /api-docs/swagger-config
        operationsSorter: method
        urls:
        - url: /api-docs
          name: API Gateway Microservice
        - url: /calendar/api-docs
          name: Calendar Microservice
        - url: /registry/api-docs
          name: Registry Microservice
        - url: /document/api-docs
          name: Document Microservice  

eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
        prefer-ip-address: true
        
      