server:
    port: 8765

spring:
    application:
        name: gateway 
    security:
            oauth2:
                resourceserver:
                    jwt:
                        issuer-uri: http://localhost:5050/realms/EQ

    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true    
            routes[0]:
                    predicates[0]: Path=/api/registry/**        
                    uri: lb://REGISTRY        
            routes[1]:
                    predicates[0]: Path=/api/calendar/**        
                    uri: lb://CALENDAR    
      
eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
        prefer-ip-address: true
        
      