server:
    port: 8765

spring:
    application:
        name: gateway 
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true    
            routes[0]:
                    predicates[0]: Path=/api/registry/**        
                    uri: lb://REGISTRY        
            routes[1]:
                    predicates[0]: Path=/api/calendar/**        
                    uri: lb://CALENDAR    
        