server:
    port: 8080
    
spring:
    application:
        name: registry
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://cognito-idp.${COGNITO_REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}

    data:
        mongodb:
            authentication-database: admin
            database: ${SPRING_DATA_MONGODB_DATABASE:registry}
            host: ${SPRING_DATA_MONGODB_HOST:localhost}
            password: ${SPRING_DATA_MONGODB_PASSWORD:secr3t}
            port: ${SPRING_DATA_MONGODB_PORT:5480}
            username: ${SPRING_DATA_MONGODB_USERNAME:admin}
            auto-index-creation: true

openapi:
    service:
        title: registry doc
        version: 1.0.0
        url: ${OPENAPI_URL:http://localhost:8765}

springdoc:
    api-docs:
        path: /registry/api-docs
    swagger-ui:
        path: /registry/swagger-ui.html  
        operationsSorter: method            

eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
        prefer-ip-address: true   