server:
    port: 8080
    
spring:
    application:
        name: registry
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:5050/realms/EQ    
    data:
        mongodb:
            authentication-database: admin
            database: registry
            host: localhost
            password: secr3t
            port: 5480
            username: admin
            auto-index-creation: true

openapi:
    service:
        title: registry doc
        version: 1.0.0
        url: http://localhost:8765

springdoc:
    api-docs:
        path: /registry/api-docs
    swagger-ui:
        path: /registry/swagger-ui.html  
        operationsSorter: method            

eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
        prefer-ip-address: true   