server:
    port: 8080
    
spring:
    application:
        name: registry
    data:
        mongodb:
            authentication-database: admin
            database: registry
            host: localhost
            password: secr3t
            port: 5480
            username: admin
            auto-index-creation: true

eureka:
  client:
    service-url: 
        default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
        instance:
            prefer-ip-address: true            
