spring:
    application:
        name: loadbalancer

server:
    port: 7171

eureka:
  client:
    service-url: 
        default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
        instance:
            prefer-ip-address: true

