# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    container_name: registrydb
    restart: always
    shm_size: 128mb
    ports:
      - "5480:5432"
    volumes:
      - db:/data/postgres  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      POSTGRES_DB: registry
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  db:
    driver: bridge

volumes:
  db: