services:
  registrydb:
    image: mongo
    container_name: registrydb
    restart: always
    logging:
      options:
        max-size: 200m
    ports:
      - "5480:27017"
    volumes:
      - registrydb:/data/mongo  
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secr3t
      MONGO_INITDB_DATABASE: registry

networks:
  registrydb:
    driver: bridge

volumes:
  registrydb: