name: Build & Deploy EQ Microservices

concurrency:
  group: eq-microservices-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  detect-changes:
    name: Detect Changed Microservices
    runs-on: ubuntu-latest
    outputs:
      any: ${{ steps.filter.outputs.any_changed }}
      services: ${{ steps.list.outputs.services }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Filter changed services
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            registry: 'registry/**'
            gateway: 'gateway/**'
            eurekaserver: 'eurekaserver/**'
            calendar: 'calendar/**'
            document: 'document/**'
            frontend: 'frontend/**'
            any_changed:
              - 'registry/**'
              - 'gateway/**'
              - 'eurekaserver/**'
              - 'calendar/**'
              - 'document/**'
              - 'frontend/**'

      - name: Build JSON array of changed services
        if: steps.filter.outputs.any_changed == 'true'
        id: list
        run: |
          # raccogliamo in bash
          SERVICES=()
          [[ "${{ steps.filter.outputs.registry }}"       == "true" ]] && SERVICES+=("registry")
          [[ "${{ steps.filter.outputs.gateway }}"        == "true" ]] && SERVICES+=("gateway")
          [[ "${{ steps.filter.outputs.eurekaserver }}"  == "true" ]] && SERVICES+=("eurekaserver")
          [[ "${{ steps.filter.outputs.calendar }}"       == "true" ]] && SERVICES+=("calendar")
          [[ "${{ steps.filter.outputs.document }}"       == "true" ]] && SERVICES+=("document")
          [[ "${{ steps.filter.outputs.frontend }}"       == "true" ]] && SERVICES+=("frontend")

          # trasformiamo in JSON array
          SERVICES_JSON=$(printf '%s\n' "${SERVICES[@]}" | jq -R . | jq -s -c .)
          echo "services=$SERVICES_JSON" >> $GITHUB_OUTPUT

  build-and-push:
    name: Build and Push Docker Images
    needs: detect-changes
    if: needs.detect-changes.outputs.any == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.services) }}

    env:
      IMAGE_REGISTRY: docker.io/overzoom
      TAG_SHA: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-${{ matrix.service }}
          key: buildx-${{ matrix.service }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ matrix.service }}-

      - name: Debug login info
        run: |
          echo "User: ${{ secrets.DOCKERHUB_USERNAME }}"
          echo "Password length: ${#DOCKERHUB_PASSWORD}"
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push ${{ matrix.service }}
        run: |
          docker buildx build \
            --cache-from=type=local,src=/tmp/.buildx-cache-${{ matrix.service }} \
            --cache-to=type=local,dest=/tmp/.buildx-cache-${{ matrix.service }},mode=max \
            --platform linux/amd64 \
            -t overzoom/eq-${{ matrix.service }}:latest \
            -t overzoom/eq-${{ matrix.service }}:${TAG_SHA} \
            -f ./${{ matrix.service }}/Dockerfile \
            ./${{ matrix.service }} \
            --push

  deploy:
    name: SSH Deploy on Production Server
    needs: build-and-push
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            attempt=0
            max_attempts=2
            until [ $attempt -ge $max_attempts ]
            do
              echo "Deploy attempt $((attempt+1))..."
              cd /home/manager/eq
              docker compose pull && docker compose up -d && break
              attempt=$((attempt+1))
              echo "Deploy failed, retrying in 15s..."
              sleep 15
            done
            if [ $attempt -ge $max_attempts ]; then
              echo "❌ All deploy attempts failed!"
              exit 1
            fi
