name: Build & Deploy EQ Microservices

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push EQ Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push EQ microservices to Docker Hub
        run: |
          chmod +x ./push_eq.sh
          ./push_eq.sh
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_PASSWORD }}
          TAG: latest

  deploy:
    name: SSH Deploy on Production Server
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            # Vai nella directory con docker-compose.yml
            cd /home/manager/eq

            # Aggiorna immagini da Docker Hub
            docker compose pull

            # Ricrea tutti i container (solo quelli con immagine aggiornata)
            docker compose up -d
