name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on Production Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
          chmod 700 ~/.ssh
          
      - name: Pull & build on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_SSH_PORT }}     
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            echo "Adding the server to known_hosts on production server..."
            mkdir -p /home/manager/.ssh
            ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> /home/manager/.ssh/known_hosts
            chmod 700 /home/manager/.ssh
            
            echo "Pull latest from origin/main..."
            cd /home/manager/eq
            git fetch --all
            git reset --hard origin/main

            echo "Assicuro build.sh eseguibile"
            chmod +x build.sh

            echo "Eseguo build.sh"
            ./build.sh
