services:
  calendardb:
    image: postgres
    container_name: calendardb
    restart: always
    shm_size: 128mb
    ports:
      - "5481:5432"
    volumes:
      - calendardb:/data/postgres  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      POSTGRES_DB: calendar
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  calendardb:
    driver: bridge

volumes:
  calendardb: